# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import beehive_job_info_pb2 as beehive__job__info__pb2


class JobServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateJob = channel.unary_unary(
        '/beehivejobinfopb.JobService/CreateJob',
        request_serializer=beehive__job__info__pb2.CreateJobRequest.SerializeToString,
        response_deserializer=beehive__job__info__pb2.JobResponse.FromString,
        )
    self.PutJob = channel.unary_unary(
        '/beehivejobinfopb.JobService/PutJob',
        request_serializer=beehive__job__info__pb2.PutJobRequest.SerializeToString,
        response_deserializer=beehive__job__info__pb2.JobResponse.FromString,
        )
    self.GetJob = channel.unary_unary(
        '/beehivejobinfopb.JobService/GetJob',
        request_serializer=beehive__job__info__pb2.GetJobRequest.SerializeToString,
        response_deserializer=beehive__job__info__pb2.GetJobResponse.FromString,
        )


class JobServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateJob': grpc.unary_unary_rpc_method_handler(
          servicer.CreateJob,
          request_deserializer=beehive__job__info__pb2.CreateJobRequest.FromString,
          response_serializer=beehive__job__info__pb2.JobResponse.SerializeToString,
      ),
      'PutJob': grpc.unary_unary_rpc_method_handler(
          servicer.PutJob,
          request_deserializer=beehive__job__info__pb2.PutJobRequest.FromString,
          response_serializer=beehive__job__info__pb2.JobResponse.SerializeToString,
      ),
      'GetJob': grpc.unary_unary_rpc_method_handler(
          servicer.GetJob,
          request_deserializer=beehive__job__info__pb2.GetJobRequest.FromString,
          response_serializer=beehive__job__info__pb2.GetJobResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'beehivejobinfopb.JobService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
